---
title: "Hello R"
author: "Mekayla Boles"
date: "Data 2401"
output: 
  html_document: 
    fig_width: 6
    fig_height: 6
    highlight: kate
---

 

### Packages Loaded

```{r load-packages, message=FALSE}
library(tidyverse) 
library(datasauRus)
```


### Exercise 1

There are 1846 rows and 3 variables. The variables included are: Dataset, x values, and y values.

### Exercise 2


```{r plot-dino, fig.height=3, fig.width=6}
dino_data <- datasaurus_dozen %>%
  filter(dataset == "dino")
ggplot(data = dino_data, mapping = aes(x = x, y = y)) +
  geom_point()
```


```{r cor-dino}
dino_data %>%
  summarize(r = cor(x, y))
```

### Exercise 3


```{r plot-star, fig.height=3, fig.width=6}
star_data <- datasaurus_dozen %>%
  filter(dataset == "star")
ggplot(data = star_data, mapping = aes(x = x, y = y)) +
  geom_point()

```

Correlations on a night star...
 
```{r cor-star}
star_data %>%
  summarize(r = cor(x, y))

```

### Exercise 4


```{r plot-circle, fig.height=3, fig.width=6}
circle_data <- datasaurus_dozen %>%
  filter(dataset == "circle")
ggplot(data = circle_data, mapping = aes(x = x, y = y)) +
  geom_point()
```

```{r cor-circle}
circle_data %>%
  summarize(r = cor(x, y))
```

### Exercise 5


```{r facesetting}
ggplot(datasaurus_dozen, aes(x = x, y = y, color = dataset))+
geom_point()+
facet_wrap(~ dataset, ncol = 3) + # facet the dataset variable, in 3 cols
theme(legend.position = "none")
```

```{r}
datasaurus_dozen %>%
  group_by(dataset) %>%
  summarize(r = cor(x, y))
```

